services:
  charts-app-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ALLOWED_ORIGINS=["http://localhost:4173"]
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    working_dir: /app/src
    networks:
      - charts-app-network

  charts-app-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    environment:
      - VITE_API_URL=http://api:8000
    ports:
      - "4173:4173"
    working_dir: /app
    networks:
      - charts-app-network

networks:
  charts-app-network:
    driver: bridge
